theme: jekyll-theme-minimal
title: Syed Wakeel Ahmed
description: Chemical Process Engineer | Operational Risk Governance
github_username: wakeelahmedsyed
linkedin_username: your-linkedin-id-here
mathjax: true
