theme: jekyll-theme-minimal
title: Syed Wakeel Ahmed
description: Chemical Process Engineer | Operational Risk Governance
# Add these lines:
github_username: wakeelahmedsyed
linkedin_username: your-linkedin-id-here
